# Generated by Django 4.2 on 2023-05-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_api', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
